server:
  port: 8081
cupSize: B
age: 18
content: "cupSize: ${cupSize},age: ${age}"
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://45.33.47.39:3306/spring_boot?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&nullNamePatternMatchesAll=true
    username: jackroad
    password: jackroad564312
    driver-class-name: com.mysql.cj.jdbc.Driver
  #关闭启动banner
  main:
    banner-mode: "off"
  redis:
    host: 45.33.47.39
    port: 6379
    password: 564312mllMll.
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
logging:
  level:
    com.vision.girl: debug
mybatis-plus:
  global-config:
    banner: false
  check-config-location: true