server:
  port: 8081
cupSize: B
age: 18
content: "cupSize: ${cupSize},age: ${age}"
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://47.104.192.128:3306/spring_boot?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&nullNamePatternMatchesAll=true
    username: supergis
    password: Visionvera#3$4%5
    driver-class-name: com.mysql.cj.jdbc.Driver
  #关闭启动banner
  main:
    banner-mode: "off"
  redis:
    host: 47.104.192.128
    port: 6379
    password: Visionvera#3$4%5
    database: 0
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: 1
        #连接池最大空闲链接
        max-idle: 8
        #连接池最小空闲链接
        min-idle: 0
    timeout: 6000
logging:
  level:
    com.vision.girl: debug
mybatis-plus:
  global-config:
    banner: false
  check-config-location: true